### ISSUE TITLE
Non-servo PRs regularly trigger "RuntimeError('Invalid configuration')"

### ISSUE THREAD

**Issue by jdm** [servo/homu#176]
```
Traceback (most recent call last):
  File "/home/servo/homu/_venv/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/servo/homu/_venv/bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/homu/server.py", line 688, in buildbot
    state, logger, repo_cfg)
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/homu/server.py", line 589, in report_build_res
    g.queue_handler()
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/homu/main.py", line 1552, in queue_handler
    return process_queue(states, repos, repo_cfgs, logger, buildbot_slots, db, git_cfg)  # noqa
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/homu/main.py", line 1203, in process_queue
    logger, db, git_cfg):
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/homu/main.py", line 1182, in start_build_or_rebuild
    return start_build(state, repo_cfgs, *args)
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/homu/main.py", line 1048, in start_build
    raise RuntimeError('Invalid configuration')
RuntimeError: Invalid configuration
```
This is coming from a PR in webrender that was approved. The code in question gathers up builders when a PR is approved and throws if no builders are applicable. This is a regression from the try-chooser work for reasons that are unclear to me.

**Comment by jdm** [comment]
Somehow state.try_choose is invalid in [this block](https://github.com/servo/homu/blob/master/homu/main.py#L1026-L1048).

**Comment by jdm** [comment]
Possibly the `None` value when inserted into a TEXT field gets converted into a string value that is treated as non-None when it is read back from the database?

cc @Manishearth

**Comment by Manishearth** [comment]
Yeah try_choose is 0 for some reason for PRs like https://github.com/servo/heapsize/pull/101 . Seems random?
