### ISSUE TITLE
Homu sometimes has an UnboundLocalError

### ISSUE THREAD

**Issue by larsbergstrom** [servo/homu#42]
This error occurs semi-frequently in the Servo homu logs.
```
INFO:homu:Starting build of servo/ipc-channel#77 on auto: 79cd0c1d4377c06e175f7f8230fa8a62d68bbe69
Traceback (most recent call last):
  File "/home/servo/homu/_venv/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/servo/homu/_venv/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/home/servo/homu/homu/server.py", line 387, in github
    realtime=True,
  File "/home/servo/homu/homu/main.py", line 404, in parse_commands
    if 'authzfail' in res.text:
UnboundLocalError: local variable 'res' referenced before assignment
```

**Comment by Manishearth** [comment]
Oh, that's when you use `force` on a non-buildbot repo. It doesn't break anything, just causes an error.

**Comment by larsbergstrom** [comment]
OK, I guess we can just close this, though a nicer error message would be nice :-)
