### ISSUE TITLE
Choking on Unicode in PR descriptions/titles

### ISSUE THREAD

**Issue by alexcrichton** [servo/homu#90]
Whenever we've seen a PR with a non-ascii character description and/or title we get backtraces like:

```
Feb 12 17:16:38 4ad3f3e4b78a homu: Traceback (most recent call last):
Feb 12 17:16:38 4ad3f3e4b78a homu:   File "/usr/local/bin/bottle.py", line 862, in _handle
Feb 12 17:16:38 4ad3f3e4b78a homu:     return route.call(**args)
Feb 12 17:16:38 4ad3f3e4b78a homu:   File "/usr/local/bin/bottle.py", line 1740, in wrapper
Feb 12 17:16:38 4ad3f3e4b78a homu:     rv = callback(*a, **ka)
Feb 12 17:16:38 4ad3f3e4b78a homu:   File "/homu/homu/server.py", line 400, in github
Feb 12 17:16:38 4ad3f3e4b78a homu:     g.queue_handler()
Feb 12 17:16:38 4ad3f3e4b78a homu:   File "/homu/homu/main.py", line 1239, in queue_handler
Feb 12 17:16:38 4ad3f3e4b78a homu:     return process_queue(states, repos, repo_cfgs, logger, buildbot_slots, db, git_cfg)
Feb 12 17:16:38 4ad3f3e4b78a homu:   File "/homu/homu/main.py", line 905, in process_queue
Feb 12 17:16:38 4ad3f3e4b78a homu:     if start_build_or_rebuild(state, repo_cfgs, buildbot_slots, logger, db, git_cfg):
Feb 12 17:16:38 4ad3f3e4b78a homu:   File "/homu/homu/main.py", line 890, in start_build_or_rebuild
Feb 12 17:16:38 4ad3f3e4b78a homu:     return start_build(state, repo_cfgs, *args)
Feb 12 17:16:38 4ad3f3e4b78a homu:   File "/homu/homu/main.py", line 794, in start_build
Feb 12 17:16:38 4ad3f3e4b78a homu:     merge_sha = create_merge(state, repo_cfg, branch, git_cfg)
Feb 12 17:16:38 4ad3f3e4b78a homu:   File "/homu/homu/main.py", line 549, in create_merge
Feb 12 17:16:38 4ad3f3e4b78a homu:     '--no-ff', '-m', merge_msg))
Feb 12 17:16:38 4ad3f3e4b78a homu:   File "/homu/homu/utils.py", line 68, in logged_call
Feb 12 17:16:38 4ad3f3e4b78a homu:     subprocess.check_call(args, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
Feb 12 17:16:38 4ad3f3e4b78a homu:   File "/usr/lib/python3.5/subprocess.py", line 576, in check_call
Feb 12 17:16:38 4ad3f3e4b78a homu:     retcode = call(*popenargs, **kwargs)
Feb 12 17:16:38 4ad3f3e4b78a homu:   File "/usr/lib/python3.5/subprocess.py", line 557, in call
Feb 12 17:16:38 4ad3f3e4b78a homu:     with Popen(*popenargs, **kwargs) as p:
Feb 12 17:16:38 4ad3f3e4b78a homu:   File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
Feb 12 17:16:38 4ad3f3e4b78a homu:     restore_signals, start_new_session)
Feb 12 17:16:38 4ad3f3e4b78a homu:   File "/usr/lib/python3.5/subprocess.py", line 1490, in _execute_child
Feb 12 17:16:38 4ad3f3e4b78a homu:     restore_signals, start_new_session, preexec_fn)
Feb 12 17:16:38 4ad3f3e4b78a homu: UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 111: ordinal not in range(128)
```

Right now my solution is to just edit out the characters and then retry, but would be great to support this natively!

**Comment by jdm** [comment]
I suspect the solution is to modify [these lines](https://github.com/servo/homu/blob/master/homu/main.py#L590-L591) to use something like `state.title.encode('ascii', 'ignore')`.

**Comment by frewsxcv** [comment]
@jdm's solution here probably does work, though I was more curious and interested _why_ it's converting to ASCII. Did a brief search online and came across [this thread](https://github.com/tdryer/hangups/issues/286). Presumably, in [docker image](https://github.com/alexcrichton/rust-central-station/blob/master/Dockerfile) where this is being used, the default filesystem encoding is ASCII:

```
> docker run -v (pwd):/source -it ubuntu:14.04 bash
root@97f89ecf1c06:/# python3 -c "import sys; print(sys.getfilesystemencoding())"
ascii
root@97f89ecf1c06:/# python3 -c "import subprocess; print(subprocess.check_output(['echo', '\U0000263a']))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.4/subprocess.py", line 607, in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1395, in _execute_child
    restore_signals, start_new_session, preexec_fn)
UnicodeEncodeError: 'ascii' codec can't encode character '\u263a' in position 0: ordinal not in range(128)
```

Though, [setting the locale in the Dockerfile](http://stackoverflow.com/a/27931669) seems to correctly set the file system encoding:

```
> docker run -v (pwd):/source -it ubuntu:14.04 bash
root@3bf26e89ecb0:/# locale-gen en_US.UTF-8
Generating locales...
  en_US.UTF-8... done
Generation complete.
root@3bf26e89ecb0:/# export LANG=en_US.UTF-8
root@3bf26e89ecb0:/# export LANGUAGE=en_US:en
root@3bf26e89ecb0:/# export LC_ALL=en_US.UTF-8
root@3bf26e89ecb0:/# python3 -c "import sys; print(sys.getfilesystemencoding())"
utf-8
root@3bf26e89ecb0:/# python3 -c "import subprocess; print(subprocess.check_output(['echo', '\U0000263a']))"
b'\xe2\x98\xba\n'
```

**Comment by frewsxcv** [comment]
Looks like the base Python images explicitly set the locale:

https://github.com/docker-library/python/pull/14

**Comment by alexcrichton** [comment]
Thanks for investigating @frewsxcv

**Comment by Eh2406** [comment]
Is this still broken?

**Comment by frewsxcv** [comment]
> Is this still broken?

If `python3 -c "import sys; print(sys.getfilesystemencoding())"` returns `ascii`, this is still going to be an issue, though it's going to be a problem with any Python program attempting to spawn a process with unicode args. So, in my opinion, the solution here is to set these env vars before running homu:

http://stackoverflow.com/a/27931669

**Comment by frewsxcv** [comment]
afaik this is fixed so closing
